name: llm_based_sat_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.0
  shared_preferences: ^2.3.5
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  image_picker: ^0.8.7+4
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/user_edit.svg
    - assets/icons/cup.svg
    - assets/icons/empty-wallet.svg
    - assets/icons/gallery.svg
    - assets/icons/logout.svg
    - assets/icons/send.svg
    - assets/icons/setting-2.svg
    - assets/icons/notification.svg
    - assets/icons/profile.svg
    - assets/icons/show.svg
    - assets/icons/back_icon.svg
    - assets/icons/exercise_images/exercise_page_A_1.png
    - assets/icons/exercise_images/exercise_page_A_2.png
    - assets/icons/pause.png
    - assets/icons/profile/accessibility.svg
    - assets/icons/profile/book.svg
    - assets/icons/profile/language-circle.svg
    - assets/icons/profile/message-question.svg
    - assets/icons/profile/notification-bing.svg
    - assets/icons/profile/rotate-left.svg
    - assets/icons/profile/security-safe.svg
    - assets/icons/profile/trash.svg

  fonts:
    - family: SevenSegment
      fonts:
        - asset: assets/fonts/7Segment.ttf
