name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Project
    runs-on: macos-latest

    env:
      FLUTTER_VERSION: 3.27.2

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Dependencies
      run: flutter pub get
      working-directory: llm_based_sat_app

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: flutter build apk --release
      working-directory: llm_based_sat_app
      env:
        CI: true

    - name: Build IPA
      run: |
        flutter build ios --release --no-codesign
      working-directory: llm_based_sat_app
      env:
        CI: true

    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: llm_based_sat_app/build/app/outputs/flutter-apk/app-release.apk

    - name: Archive IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: llm_based_sat_app/build/ios/iphoneos/Runner.app
